firstweek/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
#用于将某个页面设置成主页
from loginandregister import views
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('loginandregister/', include(('loginandregister.urls','loginandregister'),namespace= 'loginandregister')),
    url(r'^$', views.login),#设置主页
]

loginandregister/urls.py
from firstweek.urls import path
from loginandregister.views import *

urlpatterns = [
    path('login/', login, name = 'login'),
    path('register/', regisiter, name = 'register'),
    path('main/',main, name='main'),
]

loginandregister/models.py
from django.db import models
from firstweek.settings import *
# Create your models here.
class Student(models.Model):
    name = models.CharField(u'姓名', max_length=10, default='ccq')
    age = models.IntegerField(u'年龄')
    grade = models.FloatField(u'成绩', default=60)
    description = models.TextField(u'简介',max_length=100)
    choice = (
        (0,"男"),
        (1,"女")
    )
    sex = models.IntegerField( u'性别', choices=choice)
#session

loginandregister/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

User = {'sxy1': '123', 'sxy2': '456'}


def main(request):
    return render(request, 'main.html')


def login(requset):
    if requset.method == 'GET':
        return render(requset, 'login.html')
    elif requset.method == 'POST':
        username1 = requset.POST.get('username1')
        password1 = requset.POST.get('password1')
        if username1 in User and password1 == User[username1]:
            response = redirect("/loginandregister/main/") #为什么这里的路径用"../main"效果也一样
            return response
        elif username1 not in User:
            error = {'error': '用户不存在，请注册！'}
            return render(requset, 'login.html', error)
        elif username1 in User and password1 != User[username1]:
            error = {'error': '密码输入错误，请重新输入！'}
            return render(requset, 'login.html', error)


def regisiter(request):
    if request.method == 'GET':
        return render(request, 'register.html')
    elif request.method == 'POST':
        username2 = request.POST.get('username2')
        password2 = request.POST.get('password2')
        password3 = request.POST.get('password3')
        if len(username2) == 0:
            errorn = {'errorn': '用户名不得为空！'}
            return render(request, 'register.html', errorn)
        elif len(password2) == 0:
            errorn = {'errorn': '密码不得为空！'}
            return render(request, 'register.html', errorn)
        elif password2 != password3:
            errorn = {'errorn': '两次输入的密码不一致，请重试！'}
            return render(request, 'register.html', errorn)
        else:
            if username2 in User:
                error = {'error': '用户名已存在，点击前往登陆'}
                return render(request, 'register.html', error)
            elif len(username2) > 10:
                errorn = {'errorn': '用户名长度不得超过10位！'}
                return render(request, 'register.html', errorn)
            elif len(password2) < 3:
                errorn = {'errorn': '密码长度不得少于3位！'}
                return render(request, 'register.html', errorn)
            elif len(password2) > 10:
                errorn = {'errorn': '密码长度不得超过10位！'}
                return render(request, 'register.html', errorn)
            elif islegal(password2) == 0:
                errorn = {'errorn': '密码有不合法字符，请重试！'}
                return render(request, 'register.html', errorn)
            else:
                User[username2] = password2
                success = {'success': '注册成功，点击返回登陆'}
                return render(request, "register.html", success)

def islegal(password):
    legal = "0123456789abcdefghijklmnopqrstivwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ`~!@#$%^&*()_+-=[]{}\|:';:,.<>?/"
    for i in password:
        if i not in legal:
            return 0

def welcome(request):
    return render(request, 'welcome.html')

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
</body>
<h1  style="font-size:30px">请登录</h1>
<form method="post" action="{% url 'loginandregister:login' %}">
{% csrf_token %}
    <label>用户名</label>
    <input name="username1" ></input>
    <!--
    <textarea name="username1"></textarea>-->
    <br>
    <label>密码</label>
    <input name="password1" type="password"></input>
    <br>
    <br>
    <button type="submit">登陆</button>
    <a href="/loginandregister/register/"><button type="button">注册</button></a>
    <br>
    <br>
    {% if error %}
    {{ error }}
    {% endif %}

</form>
</body>
</html>

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>main</title>
</head>
<body>

<p style="text-align:center ;font-size:200px">主页</p>

</div>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>
</head>
<body>
<h1  style="font-size:30px">你还没号，赶紧注册</h1>
<form method="post" action="{% url 'loginandregister:register' %}">
{% csrf_token %}
    <label>用户名</label>
    <input name="username2" ></input>
    <br>
    <label>密码</label>
    <input name="password2" type="password"></input>
    <br>
    <label>确认密码</label>
    <input name="password3" type="password"></input>
    <br>
    <br>
    <button type="submit">注册</button>
    <a href="../../"><button type="button">返回登陆</button></a>
    <br>
    <br>
    {% if success %}
        <a href="../../">{{ success }}</a>
    {% endif %}
    {% if error %}
        <a href="../../">{{ error }}</a>
    {% endif %}
    {% if errorn %}
    {{ errorn }}
    {% endif %}
</form>

</body>
</html>

templates/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>welcome</title>
</head>
<body>
<p style="text-align:center ;font-size:100px">Welcome</p>
<br>
<a href="../loginandregister/login/"><button type="button">登陆</button></a>
</body>
</html>
<!--
    突然没用了-->